site_name: Laboratórios de Bioinformática
#site_url: https://github.com/miriamspsantos/ai-in-society
nav:
  - BIOINF1001: 'index.md'
  - Lab 28/02:
    - Linha de Comandos: 'lab02/intro.md'
    - Manipulação de Ficheiros: 'lab02/ficheiros.md'
    - Pipes: 'lab02/pipes.md'
    - Wildcards: 'lab02/wildcards.md'
    - Manual (man): 'lab02/manual.md'
    - Exercício 1: 'lab02/ex02_01.md'
    - Exercício 2: 'lab02/ex02_02.md'
    - Exercício 3: 'lab02/ex02_03.md'
  - Lab 07/03: 
    - Shell Scripting: 'lab03/intro.md'
    - Grep: 'lab03/grep.md'
    - Sed: 'lab03/sed.md'
    - Awk: 'lab03/awk.md'
    - Exercício 1: 'lab03/ex03_01.md'
    - Exercício 2: 'lab03/ex03_02.md'
    - Exercício 3: 'lab03/ex03_03.md'
  - Lab 21/03: 'lab04/intro.md'
  - Lab 28/03: 'lab05/intro.md'
  - Links: 'links.md'
  - Help:
    - Lista de comandos: 'help/lista_comandos.md'
    - Shell Scripting: 'help/shell_scripting.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/miriamspsantos
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miriamseoanesantos/
      
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2025 <a href="https://github.com/miriamspsantos"  target="_blank" rel="noopener">Miriam Seoane Santos</a>