site_name: Bioinformatics Laboratories
#site_url: https://github.com/miriamspsantos/ai-in-society
nav:
  - Home: 'index.md'
  - Lab 28/02:
    - 'lab02.md'
    - Exercise 1: 'ex02_01.md'
    - Exercise 2: 'ex02_01.md'
    - Exercise 3: 'ex02_01.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/miriamspsantos
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miriamseoanesantos/
      
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2025 <a href="https://github.com/miriamspsantos"  target="_blank" rel="noopener">Miriam Seoane Santos</a>